/**
 * Algorithm mode for steganography encoding
 */
export type StegAlgorithmMode =
  | 'lsb'           // Least Significant Bit
  | 'dct'           // Discrete Cosine Transform
  | 'spread'        // Spread Spectrum
  | 'llm-generated' // Dynamically generated by LLM
  | 'custom';       // User-provided algorithm

/**
 * Cover media types supported for steganography
 */
export type CoverMediaType =
  | 'image'
  | 'audio'
  | 'video'
  | 'binary'
  | 'text'
  | 'noise'
  | 'pattern'
  | 'gradient'
  | string; // Allow custom types like 'text:lorem'

/**
 * Represents a single piece of cover media
 */
export interface CoverMedia {
  /** The cover media data */
  data: Buffer;
  /** Type of cover media */
  type?: CoverMediaType;
  /** Optional identifier for the media */
  id?: string;
  /** Capacity in bytes this media can hold */
  capacity?: number;
}

/**
 * Configuration for steganography operations
 */
export interface StegConfig {
  /**
   * Enable or disable steganography.
   * When disabled, data passes through unchanged.
   * @default true
   */
  enabled?: boolean;

  /**
   * Algorithm to use for encoding/decoding.
   * @default 'lsb'
   */
  algorithm?: StegAlgorithmMode;

  /**
   * Cover media buffers to embed data into.
   * For LSB, each buffer should be at least 8x the data size.
   */
  coverMedia?: Array<Buffer | CoverMedia>;

  /**
   * Custom algorithm code (when algorithm is 'custom' or 'llm-generated').
   * Must export `encode(data, cover)` and `decode(stegData)` functions.
   */
  algorithmCode?: string;

  /**
   * Prompt for LLM algorithm generation.
   * Only used when algorithm is 'llm-generated'.
   */
  llmPrompt?: string;

  /**
   * LLM provider instance for dynamic algorithm generation.
   * Should implement a `createCompletion` method.
   */
  llmProvider?: LLMProvider;

  /**
   * Random seed for deterministic encoding.
   * Useful for testing and reproducibility.
   */
  seed?: string;

  /**
   * Percentage of data to encode (0-100).
   * Lower values leave more cover media unchanged.
   * @default 100
   */
  encodingRatio?: number;

  /**
   * Error handling strategy when encoding fails.
   * - 'passthrough': Send original data without steganography
   * - 'throw': Throw an error
   * - 'drop': Silently drop the data
   * @default 'passthrough'
   */
  onError?: 'passthrough' | 'throw' | 'drop';

  /**
   * Enable debug logging for steganography operations.
   * @default false
   */
  debug?: boolean;
}

/**
 * Minimal LLM provider interface for algorithm generation
 */
export interface LLMProvider {
  createCompletion(options: {
    prompt: string;
    model?: string;
    max_tokens?: number;
    temperature?: number;
  }): Promise<{
    choices: Array<{ text: string }>;
  }>;
}

/**
 * Result of a steganography encoding operation
 */
export interface StegEncodeResult {
  /** The encoded data (cover with hidden payload) */
  data: Buffer;
  /** Original payload size in bytes */
  payloadSize: number;
  /** Cover media size in bytes */
  coverSize: number;
  /** Algorithm used for encoding */
  algorithm: StegAlgorithmMode;
  /** Whether encoding was successful */
  success: boolean;
  /** Error message if encoding failed */
  error?: string;
}

/**
 * Result of a steganography decoding operation
 */
export interface StegDecodeResult {
  /** The decoded payload data */
  data: Buffer;
  /** Extracted payload size in bytes */
  payloadSize: number;
  /** Algorithm detected/used for decoding */
  algorithm: StegAlgorithmMode;
  /** Whether decoding was successful */
  success: boolean;
  /** Error message if decoding failed */
  error?: string;
}
